### ISSUE TITLE
npx playwright install  

### ISSUE THREAD

**Issue by alberttwong** [zeke/california-license-plates#3]
```
albert@albertonehouse california-license-plates % npx california-license-plates dohard
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

browserType.launch: Executable doesn't exist at /Users/albert/Library/Caches/ms-playwright/chromium-1134/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at prime (/Users/albert/sandbox/california-license-plates/lib/prime.js:12:34)
    at async search (/Users/albert/sandbox/california-license-plates/lib/search.js:5:38)
    at async main (/Users/albert/sandbox/california-license-plates/cli.js:9:32) {
  name: 'Error'
}

Node.js v22.8.0
```

**Comment by alberttwong** [comment]
```
albert@albertonehouse california-license-plates % npx playwright install
Downloading Chromium 129.0.6668.29 (playwright build v1134) from https://playwright.azureedge.net/builds/chromium/1134/chromium-mac-arm64.zip
139 MiB [====================] 100% 0.0s
Chromium 129.0.6668.29 (playwright build v1134) downloaded to /Users/albert/Library/Caches/ms-playwright/chromium-1134
Downloading FFMPEG playwright build v1010 from https://playwright.azureedge.net/builds/ffmpeg/1010/ffmpeg-mac-arm64.zip
1.1 MiB [====================] 100% 0.0s
FFMPEG playwright build v1010 downloaded to /Users/albert/Library/Caches/ms-playwright/ffmpeg-1010
Downloading Firefox 130.0 (playwright build v1463) from https://playwright.azureedge.net/builds/firefox/1463/firefox-mac-arm64.zip
80.3 MiB [====================] 100% 0.0s
Firefox 130.0 (playwright build v1463) downloaded to /Users/albert/Library/Caches/ms-playwright/firefox-1463
Downloading Webkit 18.0 (playwright build v2070) from https://playwright.azureedge.net/builds/webkit/2070/webkit-mac-14-arm64.zip
68.5 MiB [====================] 100% 0.0s
Webkit 18.0 (playwright build v2070) downloaded to /Users/albert/Library/Caches/ms-playwright/webkit-2070
```

**Comment by alberttwong** [comment]
works fine now.

**Comment by alberttwong** [comment]
https://github.com/zeke/california-license-plates/pull/4
