### ISSUE TITLE
triggerUncaughtException

### ISSUE THREAD

**Issue by tonideleo** [zeke/california-license-plates#6]
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.setViewportSize: viewportSize.height: expected number, got object
    at search (/usr/local/lib/node_modules/california-license-plates/search.js:23:14)
    at async main (/usr/local/lib/node_modules/california-license-plates/cli.js:8:5)

Node.js v18.19.1

**Comment by zeke** [comment]
Closing. See https://github.com/zeke/california-license-plates/commit/a8f24d3012f20c0785d0eda2a03663bdd2c58588
