### ISSUE TITLE
Broken, the URL/API used does not exist on the DMV site anymore

### ISSUE THREAD

**Issue by gladstonedigital** [zeke/california-license-plates#7]
The manual use page doesn't exist on the DMV site anymore: https://www.dmv.ca.gov/wasapp/ipp2/startPers.do

![image](https://github.com/user-attachments/assets/61d26e74-1eb3-4740-b036-3a29966f868f)

When running the program from CLI, a browser window comes up that says "page not found" (same image as above), then produces this error in the terminal:

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator('text=Order personalized plates')

    at search (C:\Users\bglad\AppData\Roaming\npm\node_modules\california-license-plates\search.js:32:14)
    at async main (C:\Users\bglad\AppData\Roaming\npm\node_modules\california-license-plates\cli.js:8:5) {
  name: 'TimeoutError'
}

Node.js v21.5.0
```

**Comment by zeke** [comment]
Uh oh! Do you know what the new URL is? Wanna take a shot at opening a PR to fix the issue?

**Comment by gladstonedigital** [comment]
I don't know, sorry, just noticed it was broken

**Comment by saadz-birdie** [comment]
CA has patched this. Doesn't work, from the terms box.

**Comment by zeke** [comment]
I am not able to work on this right now, but please open a pull request and ping me if you're able to fix it!

**Comment by zeke** [comment]
Heads up, y'all! I found a way.

See https://github.com/zeke/california-license-plates/commit/a8f24d3012f20c0785d0eda2a03663bdd2c58588
